### ISSUE TITLE
Phone Number Very Close to First name

### ISSUE THREAD

**Issue by Sergio16T** [gitconnected/gitconnected-feedback#35] opened 2020-12-18 02:31 UTC
Letter G is very close to the phone number below it. Not enough padding in PDF export. 

<img width="76" alt="Screen Shot 2020-12-17 at 8 32 34 PM" src="https://user-images.githubusercontent.com/47071119/102567381-0440be00-40a7-11eb-9426-5a78434b48cf.png">

**Comment by treyhuffine** [comment] 2020-12-18 02:49
Thanks for reporting @Sergio16T. Would you mind sharing a larger screenshot or setting your resume to public so I can debug? I'm not able to reproduce the issue, but would be happy to take a look.

**Comment by Sergio16T** [comment] 2020-12-18 04:35
@treyhuffine No problem! Thank you for looking into it. I set my resume to public. Very awesome tool that you have built.

**Comment by treyhuffine** [comment] 2020-12-18 04:49
@Sergio16T thanks! I found the issue and should have it released sometime tomorrow. You can set your profile to private again anytime.

**Comment by treyhuffine** [comment] 2020-12-18 15:15
Alright this should be fixed now! Feel free to re-open if you're still seeing issues or create another ticket if you have other bug reports/feedback

**Closed by treyhuffine** 2020-12-18 15:15 UTC

**Comment by Sergio16T** [comment] 2020-12-18 19:27
@treyhuffine Thank you for your awesome speed resolving this! I created a new PDF export and the spacing has been resolved! Looks fresh! My favorite resume building tool for developers by far. Great work.

**Comment by treyhuffine** [comment] 2020-12-18 19:54
Thanks, I really appreciate that! This is just the beginning too, I plan to put a lot of work into the project this coming year.
